### ISSUE TITLE
Add preview of the actual overridden config value on hover

### ISSUE THREAD

**Issue by hostep** [ericthehacker/magento2-configscopehints#6]
Hi Eric

Awesome work. I just tested your compatibility with Magento 2.1 and it works great!

I would just like to see one additional feature and that is to see what the actual overridden value is. So we don't have to switch over to the specific website/storeview scope to see the value.
You could show this while you hover over the links, with a tooltip containing the value of that specific website/storeview.

In Magento 1, the [AvS_ScopeHint](https://github.com/avstudnitz/AvS_ScopeHint) module did something similar: http://www.avs-webentwicklung.de/fileadmin/modules/AvS_ScopeHint.png

Would be great if you could consider such a feature.

Thanks!

**Comment by ericthehacker** [comment]
@hostep 
I think that's a great idea. I've added support for that on #7 and have tagged a new 3.1.0 release.

I used click/tap instead of hover to show the value preview, since I think that behavior is more touch-friendly. I've updated the README with the new expected behavior.

Thanks for the suggestion!

**Comment by hostep** [comment]
Awesome, looks very good and clean. Good job!

I ran into a few issues though, will open separate tickets for them in a few moments :)
